build:
    environment:
        php:
            version: 5.6.9
            ini:
                'error_reporting': 'E_ALL & ~E_DEPRECATED & ~E_STRICT'
                'html_errors': 'off'
    project_setup:
        before:
            -
                command: 'cp behat.yml.ci behat.yml'
            -
                command: 'cp config.json.ci config.json'
            -
                command: 'php -S localhost:8000  web/index.php'
                background: true

    tests:
        override:
            -
                command: 'bin/behat'
            -
                command: 'bin/phpunit --coverage-clover=build/coverage-clover'
                coverage:
                    file: 'build/coverage-clover'
                    format: 'clover'
